name: smartbreath_mobile
description: "SmartBreath AI - Système de monitoring respiratoire intelligent."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  # Interface et Icônes
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  fl_chart: ^1.1.1 

  # Services de Santé et Localisation
  geolocator: ^10.1.0
  url_launcher: ^6.1.11

  # Communication Backend
  http: ^1.6.0
  flutter_blue_plus: ^1.31.0

  # Gestion d'état et Utilitaires
  provider: ^6.1.5+1
  intl: ^0.20.2
  image_picker: ^1.0.7

  # Notifications et Alertes Critiques
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Gestion des assets (images et icônes)
  assets:
    - assets/images/
    - assets/icons/
